# Analysis Params
SAMPLES:
    - KO_D0_1_S2
    - KO_D0_2_S8
    - KO_D2_1_S4
    - KO_D2_2_S10
    - KO_D8_1_S6
    - KO_D8_2_S12
    - WT_D0_1_S1
    - WT_D0_2_S7
    - WT_D2_1_S3
    - WT_D2_2_S9
    - WT_D8_1_S5
    - WT_D8_2_S11

PAIR_END: True  # True/False

GENOME: genome/mm10_chr19/mm10.chr19.fa
#/project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa
#/project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/hg38.primary.fa
INDEX: genome/mm10_chr19/mm10.chr19.star_idx
#/project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/star_idx/
GTF: genome/mm10_chr19/gencode.vM21.chr19.gtf
#    /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/gencode.v29.primary_assembly.annotation.fixed.gtf
ANNO_TAB: https://raw.githubusercontent.com/hukai916/Collections/master/gencode.vM21.annotation.txt
# human: https://raw.githubusercontent.com/hukai916/Collections/master/gencode.v29.primary_assembly.anno.txt
# mouse: https://raw.githubusercontent.com/hukai916/Collections/master/gencode.vM21.annotation.txt
# view all options from: https://github.com/hukai916/Collections

STRAND: [0, 1, 2]  # can input [0, 1, 2] to get all possible results, then workflow auto inferrs the correct one 
# [2] if you know it's reverse, [1] if you know it's forward, [0] if you know it's un-stranded
# todo refine auto select
MODE: strict # liberal: Multi-Mapping, No fragment size reqirement; strict: opposite

# DE analysis
MAX_FDR: 0.05
MIN_LFC: 0.585 
META: meta/meta.xlsx
CONTRAST_DE: meta/contrast.de.xlsx

# GSEA
GSEA_NPLOTS: 100  # not implemented
GSEA_PLOT_SVG: True  # not implemented
GSEA_DBS:  # not implemented
  # - c1.all.v7.1.symbols.gmt
  # - c2.cgp.v7.1.symbols.gmt
  # - c2.cp.v7.1.symbols.gmt
  # - c3.all.v7.1.symbols.gmt
  # - c4.all.v7.1.symbols.gmt
  - c5.bp.v7.1.symbols.gmt
  # - c5.cc.v7.1.symbols.gmt
  # - c5.mf.v7.1.symbols.gmt
  # - c6.all.v7.1.symbols.gmt
  # - c7.all.v7.1.symbols.gmt
  # - h.all.v7.1.symbols.gmt  # todo: gsea err handling


# Starting point
START: FASTQ # FASTQ, BAM, COUNT, RNK

# Only if start from COUNT
COUNT_FILE: meta/COUNT.txt  # must have same format as feature_count output c1-c7 meta, c7- count

# Only if start from RNK
RNKS:
  - name1  # under ./meta/name1.rnk
  - name2  # under ./meta/name2.rnk

# Optinoal Analysis

# Alternative Splicing analysis (rMATS)
AS_ANALYSIS: True  # perform AS analysis or not
READ_LENGTH: 100  # any int if you know, e.g. 100; None triggers autodetect; affect rMATs analysis; assuming all libraries same length
# todo: must provide read length if start from BAM hint: bam_qc/stats/* :: maximum length: 100
# todo: auto detect from bam
CONTRAST_AS: meta/contrast.as.xlsx
RMATS_STRANDNESS:
  {0 : fr-unstranded,
  1 : fr-firststrand, 
  2 : fr-secondstrand}
