# Analysis Params
SAMPLES:
    - KO_D0_1_S2
    - KO_D0_2_S8
    - KO_D2_1_S4
    - KO_D2_2_S10
    - KO_D8_1_S6
    - KO_D8_2_S12
    - WT_D0_1_S1
    - WT_D0_2_S7
    - WT_D2_1_S3
    - WT_D2_2_S9
    - WT_D8_1_S5
    - WT_D8_2_S11

PAIR_END: True  # True/False

GENOME: example_data/genome/mm10_chr19/mm10.chr19.fa
#'fa' and 'fa.gz' both supported
#test: example_data/genome/mm10_chr19/mm10.chr19.fa.gz
#human: /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/hg38.primary.fa
#mouse: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa
#yeast: /project/umw_mccb/Rui/genomes/yeast/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa

INDEX: example_data/genome/mm10_chr19/star_idx
#will be created if not exist
#test: example_data/genome/mm10_chr19/star_idx
#human: /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/star_idx
#mouse: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/star_idx
#yeast: /project/umw_mccb/Rui/genomes/yeast/star_idx

GTF: example_data/genome/mm10_chr19/gencode.vM25.primary_assembly.annotation.ch19.gtf
#'gtf' or 'gtf.gz' both supported
#test: example_data/genome/mm10_chr19/gencode.vM21.chr19.gtf
#human: /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/gencode.v34.primary_assembly.annotation.gtf
#mouse: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/gencode.vM25.primary_assembly.annotation.gtf
#yeast: /project/umw_mccb/Rui/genomes/yeast/Saccharomyces_cerevisiae.R64-1-1.90.gtf

ANNO_TAB: https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/mm10.gencode.vm25.te_included.anno.txt
# human with TE: https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/hg38.gencode.v34.te_included.anno.txt
# mouse with TE: https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/mm10.gencode.vm25.te_included.anno.txt
# yeast: https://raw.githubusercontent.com/hukai916/Collections/master/Saccharomyces_cerevisiae.R64-1-1.90.anno.txt
# view all options from: https://github.com/radio1988/OneStopRNAseq/tree/master/snakemake/envs/anno_tables

STRAND: [0, 1, 2]  # can input [0, 1, 2] to get all possible results, then workflow auto inferrs the correct one 
# [2] if you know it's reverse, [1] if you know it's forward, [0] if you know it's un-stranded
# todo refine auto select
MODE: strict # liberal: Multi-Mapping, No fragment size reqirement; strict: opposite

# DE analysis
MAX_FDR: 0.05
MIN_LFC: 0.585 
META: meta/meta.xlsx
CONTRAST_DE: meta/contrast.de.xlsx
cooksCutoff: 'TRUE'
independentFilter: 'FALSE'


# GSEA
GSEA_NPLOTS: 100  # not implemented
GSEA_PLOT_SVG: True  # not implemented
GSEA_DBS:  # not implemented
  - c1.all.v7.1.symbols.gmt
  - c2.cgp.v7.1.symbols.gmt
  - c2.cp.v7.1.symbols.gmt
  - c3.all.v7.1.symbols.gmt
  - c4.all.v7.1.symbols.gmt
  - c5.bp.v7.1.symbols.gmt
  - c5.cc.v7.1.symbols.gmt
  - c5.mf.v7.1.symbols.gmt
  - c6.all.v7.1.symbols.gmt
  - c7.all.v7.1.symbols.gmt
  - h.all.v7.1.symbols.gmt  # todo: gsea err handling


# Starting point
START: FASTQ # FASTQ, BAM, COUNT, RNK

# Only if start from COUNT
COUNT_FILE: meta/COUNT.xlsx  # must have same format as feature_count output c1-c7 meta, c7- count
# both txt and xlsx supported, meta/COUNT.xlsx will be converted to meta/COUNT.xlsx.txt
# meta/COUNT.txt will be read as is

# Only if start from RNK
RNKS:
  - name1.rnk.txt  # under ./meta/name1.rnk.txt
  - name2.rnk.txt  # under ./meta/name2.rnk.txt

# Optinoal Analysis

# Alternative Splicing analysis (rMATS)
AS_ANALYSIS: True  # perform AS analysis or not
CONTRAST_AS: meta/contrast.as.xlsx
RMATS_STRANDNESS:
  {0 : fr-unstranded,
  1 : fr-firststrand, 
  2 : fr-secondstrand}

# TE analysis (SalmonTE)
TE_ANALYSIS: True # True, include TE analysis in DESeq2 results (only if FASTQ provided); False, skip
TE_REFERENCE: mm # mm, hs, dm, dr
# hs : Homo Sapiens
# mm : Mus musculus
# dm : Drosophila melanogaster
# dr : Danio rerio

# For ASE
ASE_ANALYSIS: True
VCF: example_data/genome/mm10_chr19/BALB_cJ.mgp.v5.indels.dbSNP142.normed.chr.vcf
