# Analysis Params
SAMPLES:
    - KO_D0_1_S2
    - KO_D0_2_S8
    - KO_D2_1_S4
    - KO_D2_2_S10
    - KO_D8_1_S6
    - KO_D8_2_S12
    - WT_D0_1_S1
    - WT_D0_2_S7
    - WT_D2_1_S3
    - WT_D2_2_S9
    - WT_D8_1_S5
    - WT_D8_2_S11

PAIR_END: True  # True/False

GENOME: genome/mm10_chr19/mm10.chr19.fa
#/project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa
#/project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/hg38.primary.fa

INDEX: genome/mm10_chr19/star_idx
#/project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/star_idx/

GTF: genome/mm10_chr19/genecode.vM21.chr19.gtf
#    /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/gencode.v29.primary_assembly.annotation.fixed.gtf
ANNO_TAB: https://raw.githubusercontent.com/hukai916/Collections/master/gencode.vM21.annotation.txt
# gencode.v29.primary_assembly.anno.txt.gz

STRAND: [0, 1, 2]  # can run [0, 1, 2] to get all possible results, can also select one # todo auto select
MODE: "liberal" # liberal: Multi-Mapping, No fragment size reqirement; strict: opposite

# DE analysis
MAX_FDR: 0.05
MIN_LFC: 0.585 
META: "meta/meta.xlsx"
CONTRAST: "meta/contrast.xlsx"


# GSEA
GSEA_NPLOTS: 100  # not implemented
GSEA_PLOT_SVG: TRUE  # not implemented
GSEA_DBS:  # not implemented
  - c1.all.v7.1.symbols.gmt
  - c2.cgp.v7.1.symbols.gmt
  # - c2.cp.v7.1.symbols.gmt
  # - c3.all.v7.1.symbols.gmt
  # - c4.all.v7.1.symbols.gmt
  # - c5.bp.v7.1.symbols.gmt
  # - c5.cc.v7.1.symbols.gmt
  # - c5.mf.v7.1.symbols.gmt
  # - c6.all.v7.1.symbols.gmt
  # - c7.all.v7.1.symbols.gmt
  # - h.all.v7.1.symbols.gmt
# If start from RNK
RNKS:
  - name1  # under ./meta/name1.rnk
  - name2

# Starting point
START: "BAM" # FASTQ, BAM, COUNT, RNK